"""add discount to order_items

Revision ID: 82469d01fa6b
Revises: a7b0d251f129
Create Date: 2026-05-09 16:06:27.687250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82469d01fa6b'
down_revision = 'a7b0d251f129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')

    # ### end Alembic commands ###
